import image1 from "../assets/image1.jpg";

export const productList = [
  {
    id: 1,
    image: image1,
    title: "Shop Now | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 2,
    image: image1,
    title: "Essentials | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 3,
    image: image1,
    title: "Kids Collection | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 4,
    image: image1,
    title: "Embroidery Collection | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 5,
    image: image1,
    title: "Cd X Travel With Wife | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 6,
    image: image1,
    title: "Shop Now | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 7,
    image: image1,
    title: "Shop Now | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 8,
    image: image1,
    title: "Shop Now | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 9,
    image: image1,
    title: "Shop Now | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 10,
    image: image1,
    title: "Shop Now | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 11,
    image: image1,
    title: "Shop Now | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 12,
    image: image1,
    title: "Essentials | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 13,
    image: image1,
    title: "Kids Collection | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 14,
    image: image1,
    title: "Embroidery Collection | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
  {
    id: 15,
    image: image1,
    title: "Cd X Travel With Wife | Midi Dresses",
    productName: "Leah Embroidered Midi Dress",
    price: 5350,
    sizes: ["UK8", "UK10", "UK12", "UK14", "UK16"],
    isNew: false,
  },
];
